  fluxgym:
    build:
      context: .
      # change the dockerfile to Dockerfile.cuda12.4 if you are running CUDA 12.4 drivers otherwise leave as is
      dockerfile: Dockerfile
    image: fluxgym
    container_name: fluxgym
    ports:
      - 7860:7860
    environment:
      - PUID=${PUID:-99}
      - PGID=${PGID:-100}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/user/appdata/fluxgym50rtx/:/app/fluxgym
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['YOUR_GPU_ID'] # Specify your GPU ID here (e.g., ['0'])
            capabilities: [gpu]
    restart: unless-stopped
